name: Build and Deploy Single Page Quiz to /docs
on:
   push:
     branches:
       - main

 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     permissions:
       contents: write

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Inject API Key and Prepare /docs folder
         run: |
           echo "Creating /docs directory..."
           mkdir -p ./docs

           echo "Processing config.js..."
           if [ -f config.js ]; then
             sed "s|__GEMINI_API_KEY_PLACEHOLDER__|${{ secrets.GEMINI_API_KEY }}|g" config.js > ./docs/config.js
             echo "config.js processed and placed in /docs."
           else
             echo "ERROR: config.js not found in repository root!"
             exit 1
           fi

           echo "Copying index.html to /docs..."
           if [ -f index.html ]; then
             cp index.html ./docs/
             echo "index.html copied to /docs."
           else
             echo "ERROR: index.html not found in repository root!"
             exit 1
           fi
         env:
           GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

       - name: Debug - List files in /docs
         run: |
           echo "Contents of ./docs directory:"
           ls -la ./docs
           echo "Content of ./docs/config.js:"
           cat ./docs/config.js || echo "./docs/config.js not found or empty"

       - name: Deploy /docs folder to main branch
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: main
           publish_dir: ./docs
           destination_dir: docs
           user_name: 'github-actions[bot]'
           user_email: 'github-actions[bot]@users.noreply.github.com'
           commit_message: 'Deploy single page quiz to /docs folder'
           keep_files: false
           # allow_empty_commit: true # Keep this commented unless debugging "nothing to commit" issues
