name: Deploy Processed Files to Main Branch Root

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit back to the main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Important for allowing the commit step to push
          fetch-depth: 0 # Fetch all history so a normal commit can be made

      - name: Inject API Key into config.js
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la

          if [ ! -f config.js ]; then
            echo "ERROR: config.js not found in repository root!"
            exit 1
          fi

          echo "Original config.js content:"
          cat config.js

          # Create a temporary file for the modified content
          sed "s|__GEMINI_API_KEY_PLACEHOLDER__|${{ secrets.GEMINI_API_KEY }}|g" config.js > config.js.tmp
          
          # Replace the original config.js with the modified version
          mv config.js.tmp config.js

          echo "Processed config.js content:"
          cat config.js # This will show '***' for the key in logs
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check if there are changes to commit
          if ! git diff --quiet HEAD -- config.js index.html; then
            echo "Changes detected in config.js or index.html (or other tracked files if modified)."
            git add config.js index.html # Add any other files you might modify, like index.html if you were processing it
            git commit -m "Inject API key and update site files [skip ci]"
            git push origin main
          else
            echo "No changes to commit to config.js or index.html."
          fi
        # [skip ci] in the commit message prevents the push from re-triggering the workflow
